export { Navbar } from './navbar'
export { Hero } from './hero'
export { GallerySection } from './gallery-section'
export { ExperiencesSection } from './experience-section'
export { ReservationSection } from './reservation-section'
export { Footer } from './footer'